/* The following code was generated by JFlex 1.4.3 on 4/9/15 7:06 PM */

/* JFlex spec for Cool scanner */ 

import java_cup.runtime.Symbol;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/9/15 7:06 PM from the specification file
 * <tt>D:/Eclipse WorkSpace/Compiler/src/Cool.flex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 6;
  public static final int INCOMMENT = 4;
  public static final int INCLUDEFILE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\74\1\75\1\5\1\0\1\75\1\1\22\0\1\1\1\0"+
    "\1\73\1\11\4\0\1\6\1\10\1\7\1\33\1\35\1\4\1\24"+
    "\1\34\12\72\1\30\1\23\1\26\1\25\1\27\1\2\1\32\1\53"+
    "\1\71\1\52\1\60\1\46\1\55\1\71\1\45\1\43\2\71\1\54"+
    "\1\71\1\44\1\57\1\62\1\71\1\47\1\51\1\50\1\71\1\56"+
    "\1\61\3\71\1\2\1\76\2\2\1\70\1\0\1\41\1\77\1\14"+
    "\1\17\1\20\1\40\1\63\1\64\1\12\2\63\1\15\1\63\1\13"+
    "\1\65\1\67\1\63\1\37\1\42\1\36\1\16\1\3\1\66\3\63"+
    "\1\21\1\0\1\22\1\31\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\6\1\1"+
    "\7\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\7\14\24\3\7"+
    "\1\25\1\26\1\27\1\2\1\27\3\30\1\31\1\32"+
    "\1\33\1\0\1\34\1\0\1\35\1\36\7\7\1\37"+
    "\2\7\1\40\1\41\1\42\2\7\1\43\1\7\1\35"+
    "\1\36\12\24\1\43\1\44\1\45\1\37\2\24\1\44"+
    "\1\45\2\7\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\2\1\0\2\7\1\55\1\56\2\7\1\57"+
    "\6\7\2\24\1\55\1\56\5\24\1\57\3\24\2\7"+
    "\1\0\3\7\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\7\2\24\1\62\1\63\1\65\1\24\1\60\1\61"+
    "\1\24\1\66\1\7\1\66\1\0\2\7\1\67\1\70"+
    "\2\24\1\67\2\71\1\0\1\7\1\72\1\24\1\72"+
    "\1\0\1\7\1\24\1\73\2\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\u0180\0\u01c0"+
    "\0\u0200\0\u0100\0\u0100\0\u0240\0\u0280\0\u02c0\0\u0300\0\u0340"+
    "\0\u0380\0\u03c0\0\u0400\0\u0100\0\u0100\0\u0100\0\u0100\0\u0440"+
    "\0\u0480\0\u04c0\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u0500"+
    "\0\u0540\0\u0580\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700"+
    "\0\u0740\0\u0780\0\u07c0\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900"+
    "\0\u0940\0\u0100\0\u0980\0\u09c0\0\u0a00\0\u0a40\0\u0a80\0\u0ac0"+
    "\0\u0b00\0\u0100\0\u0b40\0\u0b80\0\u0100\0\u0bc0\0\u0c00\0\u0380"+
    "\0\u0c40\0\u0c80\0\u0cc0\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0380"+
    "\0\u0e00\0\u0e40\0\u0100\0\u0100\0\u0100\0\u0e80\0\u0ec0\0\u0380"+
    "\0\u0f00\0\u0f40\0\u0600\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080"+
    "\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u0600\0\u0600\0\u0600"+
    "\0\u0600\0\u1200\0\u1240\0\u0380\0\u0380\0\u1280\0\u12c0\0\u0100"+
    "\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u0100\0\u1300"+
    "\0\u1340\0\u1380\0\u0380\0\u0380\0\u13c0\0\u1400\0\u0380\0\u1440"+
    "\0\u1480\0\u14c0\0\u1500\0\u1540\0\u1580\0\u15c0\0\u1600\0\u0600"+
    "\0\u0600\0\u1640\0\u1680\0\u16c0\0\u1700\0\u1740\0\u0600\0\u1780"+
    "\0\u17c0\0\u1800\0\u1840\0\u1880\0\u18c0\0\u1900\0\u1940\0\u1980"+
    "\0\u0380\0\u0380\0\u0380\0\u0380\0\u0380\0\u0380\0\u19c0\0\u1a00"+
    "\0\u1a40\0\u0600\0\u0600\0\u0600\0\u1a80\0\u0600\0\u0600\0\u1ac0"+
    "\0\u0600\0\u1b00\0\u0380\0\u1b40\0\u1b80\0\u1bc0\0\u0380\0\u0380"+
    "\0\u1c00\0\u1c40\0\u0600\0\u0600\0\u0380\0\u1c80\0\u1cc0\0\u0380"+
    "\0\u1d00\0\u0600\0\u1d40\0\u1d80\0\u1dc0\0\u0100\0\u0380\0\u0600";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\5\1\7\1\10\1\6\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\5"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\21"+
    "\1\41\2\21\1\42\1\43\1\44\1\45\1\44\1\46"+
    "\1\44\1\47\1\44\1\50\1\51\1\44\1\52\1\53"+
    "\1\54\1\55\2\21\1\56\1\57\1\60\1\5\1\44"+
    "\1\61\1\62\1\5\1\6\1\5\1\21\1\5\1\6"+
    "\1\63\1\64\1\10\1\6\1\11\1\12\1\13\1\14"+
    "\7\63\1\24\1\25\3\63\1\65\2\63\1\33\1\63"+
    "\1\35\1\63\1\37\35\63\1\62\1\5\1\6\2\63"+
    "\6\66\1\67\1\70\70\66\5\71\1\0\65\71\1\72"+
    "\2\0\1\73\1\71\101\0\1\6\1\0\1\6\1\0"+
    "\1\6\67\0\1\6\3\0\1\6\1\0\1\7\1\0"+
    "\1\6\4\0\7\21\15\0\35\21\2\0\1\6\1\0"+
    "\1\21\4\0\1\74\102\0\1\75\102\0\1\76\70\0"+
    "\1\21\6\0\1\21\1\77\5\21\15\0\2\21\1\100"+
    "\1\21\1\101\1\21\1\77\4\21\1\101\3\21\1\100"+
    "\15\21\4\0\1\21\3\0\1\21\6\0\6\21\1\102"+
    "\15\0\10\21\1\102\10\21\1\103\5\21\1\103\5\21"+
    "\4\0\1\21\3\0\1\21\6\0\3\21\1\104\3\21"+
    "\15\0\3\21\1\105\11\21\1\105\1\104\16\21\4\0"+
    "\1\21\3\0\1\21\6\0\6\21\1\106\15\0\10\21"+
    "\1\106\10\21\1\107\5\21\1\107\5\21\4\0\1\21"+
    "\3\0\1\21\6\0\7\21\15\0\35\21\4\0\1\21"+
    "\3\0\1\21\6\0\7\21\15\0\21\21\1\110\5\21"+
    "\1\110\5\21\4\0\1\21\3\0\1\21\6\0\3\21"+
    "\1\111\3\21\15\0\4\21\1\112\6\21\1\112\2\21"+
    "\1\111\16\21\4\0\1\21\27\0\1\113\54\0\1\114"+
    "\20\0\1\115\77\0\1\114\55\0\1\21\6\0\7\21"+
    "\15\0\1\21\1\116\5\21\1\117\16\21\1\117\6\21"+
    "\4\0\1\21\3\0\1\21\6\0\1\120\6\21\15\0"+
    "\3\21\1\121\1\21\1\120\27\21\4\0\1\21\3\0"+
    "\1\44\6\0\1\44\1\122\5\44\15\0\2\44\1\123"+
    "\1\44\1\124\1\44\1\122\4\44\1\124\3\44\1\123"+
    "\15\44\4\0\1\44\3\0\1\44\6\0\6\44\1\125"+
    "\15\0\10\44\1\125\10\44\1\126\5\44\1\126\5\44"+
    "\4\0\1\44\3\0\1\44\6\0\7\44\15\0\35\44"+
    "\4\0\1\44\3\0\1\44\6\0\3\44\1\127\3\44"+
    "\15\0\4\44\1\130\6\44\1\130\2\44\1\127\16\44"+
    "\4\0\1\44\3\0\1\44\6\0\7\44\15\0\7\44"+
    "\1\131\16\44\1\131\6\44\4\0\1\44\3\0\1\44"+
    "\6\0\3\44\1\132\3\44\15\0\3\44\1\133\11\44"+
    "\1\133\1\132\16\44\4\0\1\44\3\0\1\44\6\0"+
    "\6\44\1\134\15\0\10\44\1\134\10\44\1\135\5\44"+
    "\1\135\5\44\4\0\1\44\3\0\1\44\6\0\1\136"+
    "\6\44\15\0\5\44\1\136\27\44\4\0\1\44\3\0"+
    "\1\44\6\0\5\44\1\137\1\44\15\0\2\44\1\140"+
    "\14\44\1\140\2\44\1\137\12\44\4\0\1\44\3\0"+
    "\1\44\6\0\7\44\15\0\21\44\1\141\5\44\1\141"+
    "\5\44\4\0\1\44\3\0\1\44\6\0\7\44\15\0"+
    "\7\44\1\142\16\44\1\142\6\44\4\0\1\44\3\0"+
    "\1\44\6\0\7\44\15\0\21\44\1\143\5\44\1\143"+
    "\5\44\4\0\1\44\3\0\1\21\6\0\5\21\1\144"+
    "\1\21\15\0\2\21\1\145\14\21\1\145\2\21\1\144"+
    "\12\21\4\0\1\21\3\0\1\21\6\0\7\21\15\0"+
    "\7\21\1\146\16\21\1\146\6\21\4\0\1\21\3\0"+
    "\1\21\6\0\7\21\15\0\21\21\1\147\5\21\1\147"+
    "\5\21\4\0\1\21\72\0\1\61\7\0\2\63\6\0"+
    "\7\63\2\0\6\63\1\0\1\63\1\0\1\63\1\0"+
    "\35\63\3\0\2\63\1\0\1\6\1\63\1\64\1\0"+
    "\1\6\4\0\7\63\2\0\6\63\1\0\1\63\1\0"+
    "\1\63\1\0\35\63\2\0\1\6\2\63\2\0\2\63"+
    "\1\114\5\0\7\63\2\0\6\63\1\0\1\63\1\0"+
    "\1\63\1\0\35\63\3\0\2\63\6\66\2\0\70\66"+
    "\7\0\1\150\100\0\1\151\67\0\5\71\1\0\65\71"+
    "\4\0\1\71\5\0\1\152\5\0\1\153\22\0\1\154"+
    "\1\0\1\155\36\0\1\156\5\74\1\157\72\74\13\0"+
    "\1\160\67\0\1\21\6\0\7\21\15\0\7\21\1\161"+
    "\16\21\1\161\6\21\4\0\1\21\3\0\1\162\6\0"+
    "\7\21\15\0\20\21\1\162\14\21\4\0\1\21\3\0"+
    "\1\21\6\0\7\21\15\0\23\21\1\163\4\21\1\163"+
    "\4\21\4\0\1\21\3\0\1\21\6\0\7\21\15\0"+
    "\1\164\11\21\1\164\22\21\4\0\1\21\3\0\1\21"+
    "\6\0\7\21\15\0\3\21\1\165\11\21\1\165\17\21"+
    "\4\0\1\21\3\0\1\21\6\0\7\21\15\0\4\21"+
    "\1\166\6\21\1\166\21\21\4\0\1\21\3\0\1\21"+
    "\6\0\7\21\15\0\1\167\11\21\1\167\22\21\4\0"+
    "\1\21\3\0\1\21\6\0\7\21\15\0\21\21\1\170"+
    "\5\21\1\170\5\21\4\0\1\21\3\0\1\21\6\0"+
    "\7\21\15\0\4\21\1\171\6\21\1\171\21\21\4\0"+
    "\1\21\3\0\1\21\6\0\7\21\15\0\3\21\1\172"+
    "\11\21\1\172\17\21\4\0\1\21\3\0\1\21\6\0"+
    "\4\21\1\173\2\21\15\0\35\21\4\0\1\21\3\0"+
    "\1\21\6\0\6\21\1\174\15\0\10\21\1\174\24\21"+
    "\4\0\1\21\3\0\1\21\6\0\3\21\1\175\3\21"+
    "\15\0\35\21\4\0\1\21\3\0\1\44\6\0\7\44"+
    "\15\0\7\44\1\176\16\44\1\176\6\44\4\0\1\44"+
    "\3\0\1\177\6\0\7\44\15\0\20\44\1\177\14\44"+
    "\4\0\1\44\3\0\1\44\6\0\7\44\15\0\23\44"+
    "\1\200\4\44\1\200\4\44\4\0\1\44\3\0\1\44"+
    "\6\0\7\44\15\0\1\201\11\44\1\201\22\44\4\0"+
    "\1\44\3\0\1\44\6\0\7\44\15\0\4\44\1\202"+
    "\6\44\1\202\21\44\4\0\1\44\3\0\1\44\6\0"+
    "\7\44\15\0\3\44\1\203\11\44\1\203\17\44\4\0"+
    "\1\44\3\0\1\44\6\0\6\44\1\204\15\0\10\44"+
    "\1\204\24\44\4\0\1\44\3\0\1\44\6\0\7\44"+
    "\15\0\3\44\1\205\11\44\1\205\17\44\4\0\1\44"+
    "\3\0\1\44\6\0\7\44\15\0\4\44\1\206\6\44"+
    "\1\206\21\44\4\0\1\44\3\0\1\44\6\0\7\44"+
    "\15\0\1\207\11\44\1\207\22\44\4\0\1\44\3\0"+
    "\1\44\6\0\7\44\15\0\21\44\1\210\5\44\1\210"+
    "\5\44\4\0\1\44\3\0\1\44\6\0\1\211\6\44"+
    "\15\0\5\44\1\211\27\44\4\0\1\44\3\0\1\44"+
    "\6\0\7\44\15\0\21\44\1\212\5\44\1\212\5\44"+
    "\4\0\1\44\3\0\1\21\6\0\1\213\6\21\15\0"+
    "\5\21\1\213\27\21\4\0\1\21\3\0\1\21\6\0"+
    "\7\21\15\0\21\21\1\214\5\21\1\214\5\21\4\0"+
    "\1\21\14\0\1\215\66\0\1\21\6\0\6\21\1\216"+
    "\15\0\10\21\1\216\24\21\4\0\1\21\3\0\1\21"+
    "\6\0\7\21\15\0\21\21\1\217\5\21\1\217\5\21"+
    "\4\0\1\21\3\0\1\21\6\0\7\21\15\0\4\21"+
    "\1\220\6\21\1\220\21\21\4\0\1\21\3\0\1\21"+
    "\6\0\6\21\1\221\15\0\10\21\1\221\24\21\4\0"+
    "\1\21\3\0\1\21\6\0\7\21\15\0\24\21\1\222"+
    "\4\21\1\222\3\21\4\0\1\21\3\0\1\21\6\0"+
    "\6\21\1\223\15\0\10\21\1\223\24\21\4\0\1\21"+
    "\3\0\1\21\6\0\2\21\1\224\4\21\15\0\14\21"+
    "\1\224\20\21\4\0\1\21\3\0\1\21\6\0\6\21"+
    "\1\225\15\0\35\21\4\0\1\21\3\0\1\21\6\0"+
    "\1\21\1\226\5\21\15\0\6\21\1\226\26\21\4\0"+
    "\1\21\3\0\1\21\6\0\7\21\15\0\4\21\1\227"+
    "\30\21\4\0\1\21\3\0\1\44\6\0\6\44\1\230"+
    "\15\0\10\44\1\230\24\44\4\0\1\44\3\0\1\44"+
    "\6\0\7\44\15\0\21\44\1\231\5\44\1\231\5\44"+
    "\4\0\1\44\3\0\1\44\6\0\6\44\1\232\15\0"+
    "\10\44\1\232\24\44\4\0\1\44\3\0\1\44\6\0"+
    "\2\44\1\233\4\44\15\0\14\44\1\233\20\44\4\0"+
    "\1\44\3\0\1\44\6\0\1\44\1\234\5\44\15\0"+
    "\6\44\1\234\26\44\4\0\1\44\3\0\1\44\6\0"+
    "\7\44\15\0\4\44\1\235\6\44\1\235\21\44\4\0"+
    "\1\44\3\0\1\44\6\0\6\44\1\236\15\0\10\44"+
    "\1\236\24\44\4\0\1\44\3\0\1\44\6\0\7\44"+
    "\15\0\24\44\1\237\4\44\1\237\3\44\4\0\1\44"+
    "\3\0\1\44\6\0\3\44\1\240\3\44\15\0\16\44"+
    "\1\240\16\44\4\0\1\44\3\0\1\44\6\0\3\44"+
    "\1\241\3\44\15\0\16\44\1\241\16\44\4\0\1\44"+
    "\3\0\1\21\6\0\3\21\1\242\3\21\15\0\16\21"+
    "\1\242\16\21\4\0\1\21\3\0\1\21\6\0\3\21"+
    "\1\243\3\21\15\0\16\21\1\243\16\21\4\0\1\21"+
    "\15\0\1\244\65\0\1\21\6\0\7\21\15\0\1\21"+
    "\1\245\7\21\1\245\23\21\4\0\1\21\3\0\1\21"+
    "\6\0\1\246\6\21\15\0\5\21\1\246\27\21\4\0"+
    "\1\21\3\0\1\21\6\0\7\21\15\0\4\21\1\247"+
    "\6\21\1\247\21\21\4\0\1\21\3\0\1\21\6\0"+
    "\6\21\1\250\15\0\35\21\4\0\1\21\3\0\1\44"+
    "\6\0\7\44\15\0\1\44\1\251\7\44\1\251\23\44"+
    "\4\0\1\44\3\0\1\44\6\0\1\252\6\44\15\0"+
    "\5\44\1\252\27\44\4\0\1\44\3\0\1\44\6\0"+
    "\7\44\15\0\4\44\1\253\6\44\1\253\21\44\4\0"+
    "\1\44\3\0\1\44\6\0\6\44\1\254\15\0\10\44"+
    "\1\254\24\44\4\0\1\44\3\0\1\21\6\0\6\21"+
    "\1\255\15\0\10\21\1\255\24\21\4\0\1\21\16\0"+
    "\1\256\64\0\1\21\6\0\1\257\6\21\15\0\5\21"+
    "\1\257\27\21\4\0\1\21\3\0\1\21\6\0\5\21"+
    "\1\260\1\21\15\0\22\21\1\260\12\21\4\0\1\21"+
    "\3\0\1\44\6\0\1\261\6\44\15\0\5\44\1\261"+
    "\27\44\4\0\1\44\3\0\1\44\6\0\5\44\1\262"+
    "\1\44\15\0\22\44\1\262\12\44\4\0\1\44\17\0"+
    "\1\263\63\0\1\21\6\0\7\21\15\0\1\264\11\21"+
    "\1\264\22\21\4\0\1\21\3\0\1\44\6\0\7\44"+
    "\15\0\1\265\11\44\1\265\22\44\4\0\1\44\20\0"+
    "\1\266\62\0\1\21\6\0\7\21\15\0\4\21\1\267"+
    "\6\21\1\267\21\21\4\0\1\21\3\0\1\44\6\0"+
    "\7\44\15\0\4\44\1\270\6\44\1\270\21\44\4\0"+
    "\1\44";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\4\1\2\11\10\1\4\11\3\1\5\11"+
    "\22\1\1\11\7\1\1\11\1\1\1\0\1\11\1\0"+
    "\14\1\3\11\32\1\10\11\1\0\34\1\1\0\26\1"+
    "\1\0\11\1\1\0\4\1\1\0\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;
  
  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /** the stack of open (nested) input streams to read from */
  private java.util.Stack zzStreams = new java.util.Stack();

  /**
   * inner class used to store info for nested
   * input streams
   */
  private static final class ZzFlexStreamInfo {
    java.io.Reader zzReader;
    int zzEndRead;
    int zzStartRead;
    int zzCurrentPos;
    int zzMarkedPos;
    int yyline;
    int yycolumn;
    char [] zzBuffer;
    boolean zzAtEOF;
    boolean zzEOFDone;

    /** sets all values stored in this class */
    ZzFlexStreamInfo(java.io.Reader zzReader, int zzEndRead, int zzStartRead,
                  int zzCurrentPos, int zzMarkedPos, 
                  char [] zzBuffer, boolean zzAtEOF, int yyline, int yycolumn) {
      this.zzReader      = zzReader;
      this.zzEndRead     = zzEndRead;
      this.zzStartRead   = zzStartRead;
      this.zzCurrentPos  = zzCurrentPos;
      this.zzMarkedPos   = zzMarkedPos;
      this.zzBuffer      = zzBuffer;
      this.zzAtEOF       = zzAtEOF;
      this.zzEOFDone     = zzEOFDone;
      this.yyline         = yyline;
      this.yycolumn       = yycolumn;
    }
  }

  /* user code: */


  // Stack of file names, for 'include' files
  java.util.Stack<String> input_stack = new java.util.Stack<String>(); 
  String cur_file = "";

  // Buffer for building up tokens that take more than one pattern,
  // e.g., quoted strings 
  StringBuffer string = new StringBuffer();

  // The default "Symbol" class in CUP is stupid.  We need the alternative
  // ComplexSymbol class, which is managed by a ComplexSymbolFactory, 
  // because in Java you don't have Problems, you have ProblemFactories
  // We share the ComplexSymbolFactory with other components;
  // CUP examples do this, but I'm not sure why or if it's necessary.
  ComplexSymbolFactory symbolFactory; 

  // Alternate constructor to share the factory
  public Scanner(java.io.Reader in, ComplexSymbolFactory sf){
	this(in);
	symbolFactory = sf;
  }


  // Factor a bunch of tedium from constructing ComplexSymbol objects
  // into helper functions. 
  /**
   * Create a Symbol (token + location + text) for a lexeme 
   * that is not converted to another kind of value, e.g., 
   * keywords, punctuation, etc.
   */
  public ComplexSymbolFactory.ComplexSymbol mkSym(int id) {
    	    return (ComplexSymbolFactory.ComplexSymbol) 
               symbolFactory.newSymbol( 
	    	  sym.terminalNames[id], // per Cup documentation, no idea why
		  id,               // the actual integer used as a token code
		  new Location(yyline+1, yycolumn+1),  	// Left extent of token
		  new Location(yyline+1, yycolumn+yylength()), // Right extent
		  yytext()       	 		  // Text of the token
		  );
   }

  /**
   * Create a Symbol (token + location + value) for a lexeme 
   * that is not converted to another kind of value, e.g., 
   * an integer literal, or a token that requires more than 
   * one pattern to match (so that we can't just grab yytext).
   */
   public ComplexSymbolFactory.ComplexSymbol mkSym(int id, Object value) {
    	    return (ComplexSymbolFactory.ComplexSymbol) 
                symbolFactory.newSymbol( 
	    	  sym.terminalNames[id],  // per Cup documentation, no idea why
		  id,           	  // the actual integer token code
		  new Location(yyline+1, yycolumn+1),  // Left extent of token
		  new Location(yyline+1, yycolumn+yylength()), // Right extent
		  value      	 		 // e.g. Integer for int value
		  );
   }


   int lexical_error_count = 0; 
   int comment_begin_line = 0; /* For running off end of file in comment */ 
   int MAX_LEX_ERRORS = 20;

   String lit = ""; 

  // If the driver gives us an error report class, we use it to print lexical
  // error messages
  ErrorReport report = null; 
  public void setErrorReport( ErrorReport _report) {
       report = _report;
  }

  void err(String msg) {
    if (report == null) {
        System.err.println(msg); 
    } else {
        report.err(msg); 
    }
   }

  void lexical_error(String msg) {
    String full_msg = "Lexical error at " + cur_file + 
    		      " line " + yyline + 
    		       ", column " + yycolumn +
		       ": " + msg; 
    err(full_msg); 
    if (++lexical_error_count > MAX_LEX_ERRORS) {
       err("Too many lexical errors, giving up."); 
       System.exit(1); 
    }
  }

  int commentDepthCounter=0;



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }
    
    // numRead < 0) 
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Stores the current input stream on a stack, and
   * reads from a new stream. Lexical state, line,
   * char, and column counting remain untouched.
   *
   * The current input stream can be restored with
   * yypopstream (usually in an <<EOF>> action).
   *
   * @param reader the new input stream to read from
   *
   * @see #yypopStream()
   */
  public final void yypushStream(java.io.Reader reader) {
    zzStreams.push(
      new ZzFlexStreamInfo(zzReader, zzEndRead, zzStartRead, zzCurrentPos,
                        zzMarkedPos, zzBuffer, zzAtEOF,
                        yyline, yycolumn)
    );
    zzAtEOF  = false;
    zzBuffer = new char[ZZ_BUFFERSIZE];
    zzReader = reader;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yycolumn = 0;
  }
    

  /**
   * Closes the current input stream and continues to
   * read from the one on top of the stream stack. 
   *
   * @throws java.util.EmptyStackException
   *         if there is no further stream to read from.
   *
   * @throws java.io.IOException
   *         if there was an error in closing the stream.
   *
   * @see #yypushStream(java.io.Reader)
   */
  public final void yypopStream() throws java.io.IOException {
    zzReader.close();
    ZzFlexStreamInfo s = (ZzFlexStreamInfo) zzStreams.pop();
    zzBuffer      = s.zzBuffer;
    zzReader      = s.zzReader;
    zzEndRead     = s.zzEndRead;
    zzStartRead   = s.zzStartRead;
    zzCurrentPos  = s.zzCurrentPos;
    zzMarkedPos   = s.zzMarkedPos ;
    zzAtEOF       = s.zzAtEOF;
    zzEOFDone     = s.zzEOFDone;
    yyline         = s.yyline;
    yycolumn       = s.yycolumn;
  }


  /**
   * Returns true iff there are still streams left 
   * to read from on the stream stack.
   */
  public final boolean yymoreStreams() {
    return !zzStreams.isEmpty();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   *
   * @see #yypushStream(java.io.Reader)
   * @see #yypopStream()
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public ComplexSymbolFactory.ComplexSymbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      // cached fields:
      int zzCurrentPosL;
      int zzMarkedPosL = zzMarkedPos;
      int zzEndReadL = zzEndRead;
      char [] zzBufferL = zzBuffer;
      char [] zzCMapL = ZZ_CMAP;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 24: 
          { /* skip */
          }
        case 61: break;
        case 7: 
          { return mkSym( sym.ID, yytext());
          }
        case 62: break;
        case 11: 
          { return mkSym( sym.DOT );
          }
        case 63: break;
        case 28: 
          { yybegin(INCOMMENT); comment_begin_line = yyline; commentDepthCounter=1;
          }
        case 64: break;
        case 15: 
          { return mkSym( sym.NEG);
          }
        case 65: break;
        case 57: 
          { return mkSym( sym.WHILE );
          }
        case 66: break;
        case 58: 
          { return mkSym( sym.ISVOID );
          }
        case 67: break;
        case 45: 
          { return mkSym( sym.NEW );
          }
        case 68: break;
        case 46: 
          { return mkSym( sym.NOT );
          }
        case 69: break;
        case 43: 
          { lit=lit+"\f";
          }
        case 70: break;
        case 55: 
          { return mkSym( sym.CLASS );
          }
        case 71: break;
        case 50: 
          { return mkSym( sym.ELSE );
          }
        case 72: break;
        case 13: 
          { return mkSym( sym.LT );
          }
        case 73: break;
        case 23: 
          { String filename=yytext(); 
   	     yybegin(YYINITIAL); 
	     input_stack.push(cur_file); 
	     cur_file = filename; 
	     yypushStream(new java.io.FileReader(yytext()));
          }
        case 74: break;
        case 41: 
          { lit=lit+"\n";
          }
        case 75: break;
        case 22: 
          { yybegin(STRING); lit="";
          }
        case 76: break;
        case 60: 
          { return mkSym( sym.INHERITS );
          }
        case 77: break;
        case 30: 
          { return mkSym( sym.IF );
          }
        case 78: break;
        case 27: 
          { lit=lit+"\\";
          }
        case 79: break;
        case 56: 
          { return mkSym( sym.FALSE );
          }
        case 80: break;
        case 38: 
          { commentDepthCounter++;
          }
        case 81: break;
        case 35: 
          { return mkSym( sym.FI );
          }
        case 82: break;
        case 31: 
          { return mkSym( sym.DO );
          }
        case 83: break;
        case 6: 
          { return mkSym( sym.RPAREN );
          }
        case 84: break;
        case 49: 
          { return mkSym( sym.LOOP );
          }
        case 85: break;
        case 9: 
          { return mkSym( sym.RBRACE );
          }
        case 86: break;
        case 34: 
          { return mkSym( sym.LEQ);
          }
        case 87: break;
        case 18: 
          { return mkSym( sym.DIV );
          }
        case 88: break;
        case 5: 
          { return mkSym( sym.TIMES);
          }
        case 89: break;
        case 14: 
          { return mkSym( sym.COLON);
          }
        case 90: break;
        case 40: 
          { lit=lit+"\n";   /* ignore */
          }
        case 91: break;
        case 16: 
          { return mkSym( sym.AT);
          }
        case 92: break;
        case 17: 
          { return mkSym( sym.PLUS);
          }
        case 93: break;
        case 48: 
          { return mkSym( sym.CASE );
          }
        case 94: break;
        case 1: 
          { lexical_error("Illegal character '" +
      	              yytext() +
		      "' ");
          }
        case 95: break;
        case 32: 
          { return mkSym( sym.RIGHTARROW);
          }
        case 96: break;
        case 42: 
          { lit=lit+"\t";
          }
        case 97: break;
        case 20: 
          { return mkSym( sym.TYPEID, yytext());
          }
        case 98: break;
        case 29: 
          { return mkSym( sym.IN );
          }
        case 99: break;
        case 44: 
          { lit=lit+"\b";
          }
        case 100: break;
        case 37: 
          { return mkSym( sym.OF );
          }
        case 101: break;
        case 53: 
          { return mkSym( sym.THEN );
          }
        case 102: break;
        case 3: 
          { return mkSym( sym.MINUS);
          }
        case 103: break;
        case 2: 
          { ; /* skip */
          }
        case 104: break;
        case 59: 
          { yybegin(INCLUDEFILE);
          }
        case 105: break;
        case 54: 
          { return mkSym( sym.POOL );
          }
        case 106: break;
        case 21: 
          { return mkSym( sym.INTLIT, yytext() );
          }
        case 107: break;
        case 39: 
          { commentDepthCounter--;  if(commentDepthCounter==0){yybegin(YYINITIAL);}
          }
        case 108: break;
        case 26: 
          { yybegin(YYINITIAL);
                    if(lit.length()>1024){
                        lexical_error("String length cannot be greater than 1024 ");
                    }
                    else{
                        return mkSym( sym.STRINGLIT, lit );
                    }
          }
        case 109: break;
        case 52: 
          { return mkSym( sym.TRUE );
          }
        case 110: break;
        case 4: 
          { return mkSym( sym.LPAREN );
          }
        case 111: break;
        case 47: 
          { return mkSym( sym.LET );
          }
        case 112: break;
        case 8: 
          { return mkSym( sym.LBRACE );
          }
        case 113: break;
        case 33: 
          { return mkSym( sym.ASSIGN);
          }
        case 114: break;
        case 36: 
          { return mkSym( sym.OD );
          }
        case 115: break;
        case 19: 
          { return mkSym( sym.COMMA);
          }
        case 116: break;
        case 25: 
          { lit=lit+yytext();
          }
        case 117: break;
        case 10: 
          { return mkSym( sym.SEMI );
          }
        case 118: break;
        case 51: 
          { return mkSym( sym.ESAC );
          }
        case 119: break;
        case 12: 
          { return mkSym( sym.EQ );
          }
        case 120: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case INCOMMENT: {
              lexical_error("Comment \"(*...\"  missing ending \"*)\"" +"\nComment began on line " +comment_begin_line );
	            yybegin(YYINITIAL);
            }
            case 185: break;
            default:
              {
                if (yymoreStreams()) {
	        yypopStream(); 
		cur_file = input_stack.pop(); 
	     }  else {
                return mkSym( sym.EOF ); 
	     }
              }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
